import Head from 'next/head'
import Script from 'next/script'
import '../styles/globals.css'

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script async defer src="https://connect.facebook.net/en_US/sdk.js" />
      </Head>
      <Component {...pageProps} />

    </>)



}

export default MyApp
