import Head from 'next/head'
import '../styles/globals.css';


declare global {
  interface Window {
    fbAsyncInit: any;
    FB: any;
  }
}


function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Component {...pageProps} />

    </>)



}

export default MyApp
