import Head from 'next/head'
import '../styles/globals.css';


declare global {
  interface Window {
    fbAsyncInit: any;
    FB: any;
    google: any;
  }
}


function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="google-signin-client_id" content="351171074715-38gr42ulu7b22mkpf1ildmbs41d285hl.apps.googleusercontent.com"></meta>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Component {...pageProps} />

    </>)



}

export default MyApp
